version: '3'
networks:
  app-tier:
    driver: bridge
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier
  kafka-broker:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - app-tier
  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-tier
  inventory-service:
    build: ./inventory-service
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-tier
  shipping-service:
    build: ./shipping-service
    ports:
      - "8082:8082"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-tier